# Generated by Django 4.2.28 on 2026-03-02 16:50

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('RETURNING', 'Returning'), ('CHARGING', 'Charging'), ('MAINTENANCE', 'Maintenance')], default='IDLE', max_length=20)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('home_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('battery_level', models.IntegerField(default=100, help_text='Battery percentage')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('telemetry_data', models.JSONField(default=dict, help_text='Real-time telemetry')),
                ('has_thermal', models.BooleanField(default=True)),
                ('has_lidar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_encoding', models.BinaryField(help_text='Facial recognition embedding')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('known_aliases', models.JSONField(default=list)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('warrants', models.JSONField(default=list, help_text='Active warrants/flags')),
                ('last_seen_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('last_seen_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_docs', models.JSONField(default=dict)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_available', models.BooleanField(default=True)),
                ('specializations', models.JSONField(default=list, help_text='Medical, Fire, Police, etc.')),
                ('rating', models.FloatField(default=5.0)),
                ('response_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('DISPATCHED', 'Dispatched'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved'), ('FALSE_ALARM', 'False Alarm')], default='REPORTED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ai_classification', models.JSONField(default=dict, help_text='AI analysis results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('blockchain_hash', models.CharField(blank=True, help_text='Evidence integrity hash', max_length=128)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('TELEMETRY', 'Telemetry')], max_length=20)),
                ('file_url', models.URLField()),
                ('captured_at', models.DateTimeField()),
                ('blockchain_hash', models.CharField(max_length=128)),
                ('metadata', models.JSONField(default=dict, help_text='Resolution, coordinates, device info')),
                ('is_redacted', models.BooleanField(default=False, help_text='AI privacy redaction applied')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emergency_app.drone')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='emergency_app.incident')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddField(
            model_name='drone',
            name='current_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drones', to='emergency_app.incident'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-created_at'], name='emergency_a_created_03bdec_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='emergency_a_status_e40bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['location'], name='emergency_a_locatio_3f699f_idx'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['status'], name='emergency_a_status_56faa8_idx'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['current_location'], name='emergency_a_current_ccbd52_idx'),
        ),
    ]
