# Generated by Django 4.2.28 on 2026-03-06 21:54

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergency_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('SPOUSE', 'Spouse'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('UNCLE', 'Uncle'), ('AUNT', 'Aunt'), ('COUSIN', 'Cousin'), ('OTHER', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_code', models.CharField(help_text='Unique user ID like HN-20260307-001', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('CIVILIAN', 'Civilian'), ('VOLUNTEER', 'Volunteer'), ('RESPONDER', 'Responder'), ('POLICE_STATION', 'Police Station Level Operator'), ('DISTRICT', 'District Level Operator'), ('STATE', 'State Level Operator'), ('CENTRAL', 'Central Level Operator'), ('ADMIN', 'Admin')], default='CIVILIAN', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('aadhar_card', models.ImageField(blank=True, upload_to='aadhar_cards/')),
                ('pan_card', models.ImageField(blank=True, upload_to='pan_cards/')),
                ('driving_licence', models.ImageField(blank=True, upload_to='driving_licences/')),
                ('passport', models.ImageField(blank=True, upload_to='passports/')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('village_city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('location_coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='emergency_a_locatio_3f699f_idx',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='audio_url',
            new_name='drone_video_url',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='location',
            new_name='location_coordinates',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='video_url',
            new_name='phone_video_url',
        ),
        migrations.AddField(
            model_name='drone',
            name='destination_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='evidence',
            name='drone_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='phone_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='action_taken_by_authority',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('FALSE_ALARM', 'False Alarm')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='drone_video',
            field=models.FileField(blank=True, upload_to='drone_videos/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('MEDICAL', 'Medical'), ('FIRE', 'Fire'), ('ACCIDENT', 'Accident'), ('CRIME', 'Crime'), ('TERRORIST_ATTACK', 'Terrorist Attack'), ('BOMB_THREAT', 'Bomb Threat'), ('NATURAL_DISASTER', 'Natural Disaster'), ('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('LANDSLIDE', 'Landslide'), ('STORM', 'Storm'), ('TSUNAMI', 'Tsunami'), ('WILDFIRE', 'Wildfire'), ('CHEMICAL_SPILL', 'Chemical Spill'), ('INDUSTRIAL_ACCIDENT', 'Industrial Accident'), ('ROAD_ACCIDENT', 'Road Accident'), ('NUCLEAR_LEAK', 'Nuclear Leak'), ('BIOLOGICAL_HAZARD', 'Biological Hazard'), ('OTHER', 'Other')], default='MEDICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_live_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='phone_video',
            field=models.FileField(blank=True, upload_to='phone_videos/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='responders_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='suspect',
            name='by_whom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspect',
            name='image',
            field=models.ImageField(blank=True, upload_to='suspects/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('DISPATCHED', 'Dispatched'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['location_coordinates'], name='emergency_a_locatio_1af565_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_members',
            field=models.ManyToManyField(blank=True, help_text='Family members who are also registered users', through='emergency_app.FamilyRelation', to='emergency_app.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyrelation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='emergency_app.userprofile'),
        ),
        migrations.AddField(
            model_name='familyrelation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='emergency_app.userprofile'),
        ),
        migrations.AddField(
            model_name='incident',
            name='family_members_notified',
            field=models.ManyToManyField(blank=True, related_name='notified_incidents', to='emergency_app.userprofile'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_reported_incidents', to='emergency_app.userprofile'),
        ),
        migrations.AddField(
            model_name='incident',
            name='which_authority_took_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_actions', to='emergency_app.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='familyrelation',
            unique_together={('from_user', 'to_user')},
        ),
    ]
