# Generated by Django 4.2.28 on 2026-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0002_familyrelation_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reported_medium',
            field=models.CharField(choices=[('SOS_BUTTON', 'SOS Button'), ('INSTANT_BUTTON', 'Instant Button'), ('FORM_SUBMISSION', 'Form Submission'), ('PHONE_CALL', 'Phone Call'), ('EMAIL', 'Email'), ('OTHER', 'Other')], default='APP', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='action_taken_by_authority',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FALSE_ALARM', 'False Alarm')], default='ACTIVE', max_length=20),
        ),
    ]
