# Generated by Django 5.2.8 on 2026-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0003_incident_reported_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='pincode',
            field=models.CharField(blank=True, help_text='Pincode derived from incident coordinates', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='timeLine',
            field=models.JSONField(default=list, help_text='Chronological log of incident updates'),
        ),
    ]
