# Generated by Django 4.2.28 on 2026-03-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0005_age_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='village_city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
