import { createSlice } from '@reduxjs/toolkit'

const sampleIncidents = [
  {
    id: 1,
    title: 'Building Fire Reported',
    description: 'Major fire broke out in a 4-story residential building. Multiple families trapped on upper floors.',
    severity: 'CRITICAL',
    status: 'DISPATCHED',
    location: { coordinates: [72.8777, 19.0760] },
    location_name: 'Andheri West, Mumbai',
    address: 'Andheri West, Mumbai',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Road Accident - Highway',
    description: 'Multi-vehicle collision on NH-44. At least 3 vehicles involved, injuries reported.',
    severity: 'HIGH',
    status: 'EN_ROUTE',
    location: { coordinates: [77.5946, 12.9716] },
    location_name: 'MG Road, Bengaluru',
    address: 'MG Road, Bengaluru',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 3,
    title: 'Medical Emergency - SOS',
    description: 'Elderly person collapsed in public area. Cardiac arrest suspected. Ambulance requested.',
    severity: 'CRITICAL',
    status: 'ON_SCENE',
    location: { coordinates: [77.2090, 28.6139] },
    location_name: 'Connaught Place, New Delhi',
    address: 'Connaught Place, New Delhi',
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 4,
    title: 'Flood Warning Alert',
    description: 'Water level rising in low-lying areas. Evacuation advisory issued for nearby residents.',
    severity: 'MEDIUM',
    status: 'REPORTED',
    location: { coordinates: [80.2707, 13.0827] },
    location_name: 'T. Nagar, Chennai',
    address: 'T. Nagar, Chennai',
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: 5,
    title: 'Gas Leak Detected',
    description: 'Industrial gas leak near factory area. Residents advised to stay indoors.',
    severity: 'HIGH',
    status: 'DISPATCHED',
    location: { coordinates: [78.4867, 17.3850] },
    location_name: 'HITEC City, Hyderabad',
    address: 'HITEC City, Hyderabad',
    created_at: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 6,
    title: 'Building Collapse - Rescue Needed',
    description: 'Partial building collapse after heavy rainfall. Workers may be trapped under debris.',
    severity: 'CRITICAL',
    status: 'EN_ROUTE',
    location: { coordinates: [88.3639, 22.5726] },
    location_name: 'Salt Lake, Kolkata',
    address: 'Salt Lake, Kolkata',
    created_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 7,
    title: 'Road Accident - School Zone',
    description: 'Vehicle hit a pedestrian near school crossing. Minor injuries, traffic blocked.',
    severity: 'MEDIUM',
    status: 'ON_SCENE',
    location: { coordinates: [75.8577, 26.9124] },
    location_name: 'MI Road, Jaipur',
    address: 'MI Road, Jaipur',
    created_at: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 8,
    title: 'Medical Emergency - Poisoning',
    description: 'Food poisoning outbreak at a local restaurant. Multiple patients rushed to hospital.',
    severity: 'HIGH',
    status: 'REPORTED',
    location: { coordinates: [73.8567, 18.5204] },
    location_name: 'FC Road, Pune',
    address: 'FC Road, Pune',
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 9,
    title: 'Fire at Warehouse',
    description: 'Large fire at chemical storage warehouse. Hazmat team requested. Area being evacuated.',
    severity: 'CRITICAL',
    status: 'DISPATCHED',
    location: { coordinates: [72.8311, 21.1702] },
    location_name: 'Industrial Area, Surat',
    address: 'Industrial Area, Surat',
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 10,
    title: 'Flood Rescue Operation',
    description: 'Stranded families in waterlogged colony. Boats deployed for evacuation assistance.',
    severity: 'HIGH',
    status: 'ON_SCENE',
    location: { coordinates: [85.1376, 25.6093] },
    location_name: 'Kankarbagh, Patna',
    address: 'Kankarbagh, Patna',
    created_at: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  // Past / Resolved incidents
  {
    id: 11,
    title: 'Chemical Spill Contained',
    description: 'Minor chemical spill at factory cleaned up. No injuries reported. Area cleared by hazmat team.',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    location: { coordinates: [73.0169, 19.0178] },
    location_name: 'Navi Mumbai Industrial Zone',
    address: 'Navi Mumbai Industrial Zone',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 12,
    title: 'Earthquake Tremor - Minor',
    description: 'Minor tremor of 3.2 magnitude felt. No structural damage. Precautionary checks completed.',
    severity: 'LOW',
    status: 'RESOLVED',
    location: { coordinates: [77.5946, 12.9716] },
    location_name: 'Whitefield, Bengaluru',
    address: 'Whitefield, Bengaluru',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 13,
    title: 'Train Derailment - Rescue Complete',
    description: 'Local train derailed near station. All passengers evacuated safely. Track repair underway.',
    severity: 'HIGH',
    status: 'RESOLVED',
    location: { coordinates: [72.8362, 18.9647] },
    location_name: 'Dadar Station, Mumbai',
    address: 'Dadar Station, Mumbai',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 14,
    title: 'Power Grid Failure - Restored',
    description: 'Major power outage affecting 50,000 homes. Backup generators deployed. Power fully restored.',
    severity: 'HIGH',
    status: 'RESOLVED',
    location: { coordinates: [77.2090, 28.6139] },
    location_name: 'South Delhi',
    address: 'South Delhi',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 15,
    title: 'Festival Stampede Averted',
    description: 'Crowd control activated at temple festival. Barriers deployed, crowd dispersed safely.',
    severity: 'CRITICAL',
    status: 'RESOLVED',
    location: { coordinates: [83.0007, 25.3176] },
    location_name: 'Varanasi Ghats',
    address: 'Varanasi Ghats',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
]

export const incidentSlice = createSlice({
  name: 'incidents',
  initialState: {
    items: sampleIncidents,
    stats: { active: 10, resolved: 5 },
  },

  reducers: {}
})
export default incidentSlice.reducer

